# Site settings
title: .
SEOTitle: Hongbo Zhao | 赵宏博
header-img: img/view.jpg
email: zhaohongbo@2022@ia.ac.cn
description: "Aim High and Down to Earth"
keyword: ""
url: "https://bjzhb666.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
zhihu_username:     zhb-30-39
github_username:    bjzhb666
googlescholar_username:   Gs22F0UAAAAJ&hl
# linkedin_username:  玉康-陈-35aaa2151



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: yukangchen

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: yukangchen.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "yukangchen@cse.cuhk.edu.hk"
sidebar-avatar: /img/me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    title: "Yanwei Li",
        href: "https://yanwei-li.com/"
    },{
        title: "Ruihang Chu",
        href: "ruihangchu@link.cuhk.edu.hk"
    },{
      title: "Lu Qi",
      href: "http://luqi.info/"
    },{
      title: "Dechao Meng",
      href: "https://silverbulletmdc.github.io/"
    },{
      title: "Peizhen Zhang",
      href: "https://github.com/zhangpzh"
    }
]
